const courses={
"HTML & CSS":{title:"HTML & CSS — Lesson 1",body:`<p><b>HTML</b> gives a webpage its structure. <b>CSS</b> controls its appearance.</p><h3>Example HTML</h3><pre>&lt;h1&gt;Hello, world!&lt;/h1&gt;\n&lt;p&gt;My first webpage.&lt;/p&gt;</pre><h3>In this course</h3><ul><li>Headings, paragraphs and links</li><li>Images, buttons and forms</li><li>Colors, spacing and layouts with CSS</li></ul>`},
"Python":{title:"Python — Lesson 1",body:`<p>Python is a beginner-friendly programming language used in automation, data science and web development.</p><h3>Example</h3><pre>print("Hello, world!")</pre><p>This displays the words Hello, world!</p>`},
"JavaScript":{title:"JavaScript — Lesson 1",body:`<p>JavaScript makes websites interactive and responsive to user actions.</p><h3>Example</h3><pre>alert("Welcome to CodeLearn!");</pre><p>This displays a simple message in the browser.</p>`},
"Computer Science Basics":{title:"Computer Science Basics — Lesson 1",body:`<p>Computer science explores computation, algorithms, information and computer systems.</p><h3>Core topics</h3><ul><li>Algorithms and problem solving</li><li>Programming and data structures</li><li>Hardware, software and networks</li><li>Databases and information</li></ul>`}};
let currentCourse="";
const getData=()=>{try{return JSON.parse(localStorage.getItem("codelearn")||'{"completed":[],"profile":null}')}catch{return {completed:[],profile:null}}};
const saveData=d=>localStorage.setItem("codelearn",JSON.stringify(d));
function showLesson(name){currentCourse=name;document.getElementById("lessonTitle").textContent=courses[name].title;document.getElementById("lessonContent").innerHTML=courses[name].body;document.getElementById("lesson").classList.remove("hidden");const done=getData().completed.includes(name);document.getElementById("completeButton").textContent=done?"Lesson completed ✓":"Mark lesson complete ✓";document.getElementById("lessonStatus").textContent=done?"You have completed this lesson.":"";document.getElementById("lesson").scrollIntoView();}
function closeLesson(){document.getElementById("lesson").classList.add("hidden");}
function completeLesson(){const d=getData();if(!d.completed.includes(currentCourse))d.completed.push(currentCourse);saveData(d);document.getElementById("completeButton").textContent="Lesson completed ✓";document.getElementById("lessonStatus").textContent="Great work! Your progress has been saved on this device.";renderDashboard();}
function renderDashboard(){const d=getData();const n=d.completed.length;document.getElementById("progressCount").textContent=`${n} of 4`;document.getElementById("progressBar").style.width=`${n/4*100}%`;document.getElementById("progressMessage").textContent=n===4?"Excellent! You completed all four starter lessons.":n?`Keep going — ${4-n} starter lesson${4-n===1?"":"s"} left.`:"Open a course and mark a lesson complete to begin.";document.getElementById("welcome").textContent=d.profile?`Welcome, ${d.profile.name}!`:"My learning dashboard";if(d.profile){document.getElementById("studentName").value=d.profile.name;document.getElementById("studentEmail").value=d.profile.email||"";document.getElementById("accountMessage").textContent="Profile saved on this device."}}
document.getElementById("accountForm").addEventListener("submit",e=>{e.preventDefault();const d=getData();d.profile={name:document.getElementById("studentName").value.trim(),email:document.getElementById("studentEmail").value.trim()};saveData(d);renderDashboard();document.getElementById("accountMessage").textContent="Profile saved on this device."});
document.getElementById("signOut").addEventListener("click",()=>{const d=getData();d.profile=null;saveData(d);document.getElementById("studentName").value="";document.getElementById("studentEmail").value="";document.getElementById("accountMessage").textContent="Profile signed out on this device.";renderDashboard()});
function checkQuiz(){let score=0;for(let i=1;i<=2;i++){const a=document.querySelector(`input[name="q${i}"]:checked`);if(a&&a.value==="correct")score++;}document.getElementById("result").textContent=`You scored ${score}/2${score===2?" — excellent work!":" — keep learning and try again."}`;}
renderDashboard();